apiVersion: v1
kind: Namespace
metadata:
  name: grid-enrollment
  labels:
    app.kubernetes.io/part-of: ai-grid
---
apiVersion: v1
kind: Namespace
metadata:
  name: grid
  labels:
    app.kubernetes.io/part-of: ai-grid
